### PR TITLE
Refactor/sort

### LINKED ISSUE #188: Float Infer Unification Issue
`%math.arith.mul 0 (a,b)` 
is parsed as
`%math.arith.mul (.infer (<nullptr>), .infer (<nullptr>)) 0` (applied to `(a,b)`)
of domain
`«2; %math.F (.infer (<nullptr>), .infer (<nullptr>))»`.

However, this excludes floats where `(p,e)` is perceived as one def.

For instance, 
```
  .let R = %math.F (p,e);
  .con prod_comb [[mem:%mem.M, acc:R, [a:R, b:R]], ret:.Cn[%mem.M,R]] = {
      .let v = %math.arith.mul 0 (a,b);
``` 
is not accepted (in the current version) as `(a,b)` is of type `«2; %math.F __13580»`.

Note: The code is present in `matrix.thorin` in the `matrix_dialect` branch.

### PR DESCRIPTION
**Pull request by leissa**
Fighting a couple of issues while trying to fix #188

### CODE REVIEW

**Comment by NeuralCoder3** [comment]
This pull request does not fix #188 in its current state. 
The reported error at build time is still 
```rust 
matrix.thorin:325:41-325:50: error: cannot pass argument '__6129#2:(.Idx 3)' of type '«2; %math.F __5873»' to '%math.arith.mul (.infer (<nullptr>), .infer (<nullptr>)) 0' of domain '«2; %math.F (.infer (<nullptr>), .infer (<nullptr>))»'
```

**Comment by leissa** [comment]
it's not a fix for #188. Just a couple of other things I encountered (that I wanted to fix first) while trying to fix the original issue.

That being said, there is this typing rule that always confuses me. Say, we have:
```
.Type 7 -> .Type 2
```
What is the type of this?
* 2
* 3
* 7
* 8
* sth else entirely?

With the current patch, it would be 8 - but I'm not so sure anymore whether this is the desired behavior. What's your take on this?

**Comment by NeuralCoder3** [comment]
> it's not a fix for https://github.com/AnyDSL/thorin2/issues/188. Just a couple of other things I encountered (that I wanted to fix first) while trying to fix the original issue.

Okay, I misunderstood the purpose of the PR. I will review the code.

> That being said, there is this typing rule that always confuses me. Say, we have:
> 
> ```
> .Type 7 -> .Type 2
> ```
> 
> What is the type of this?

Do you mean a function
````
f: Type(7) -> Type(2)
:= lambda (a:Type(7)). body : Type(2)
```
or
```
U := Type(7) -> Type(2)
``` 
?

According to [coq's typing rules](https://coq.inria.fr/refman/language/cic.html)
(Less convoluted formulation (page 16 (pdf 23)): https://www.ps.uni-saarland.de/~ullrich/bachelor/thesis.pdf)

I would ascribe `U : Type(8)`.
The type universe can not be lower than 8. It has to be at least one higher than the argument except for impredicative universes.

**Comment by leissa** [comment]
Yes, I meant `U`. 
Just added a unit test for this.

**Review by NeuralCoder3 — APPROVED** [review]

**Pull request merged**
